name: Pre-release check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kssm
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build and check with Gradle
      run: ./gradlew build
  
  codacy-analysis-cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kssm
    name: codacy-analysis-cli
    steps:
      - uses: actions/checkout@v2
      - name: Run codacy-analysis-cli
        uses: mrfyda/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
